CREATE MEMORY TABLE Customers (
   id LONG GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY,
   first_name VARCHAR(50) NOT NULL,
   second_name VARCHAR(50) NOT NULL,
   last_name VARCHAR(50) NOT NULL, 
   phone_number VARCHAR(20) NOT NULL,
    );

CREATE MEMORY TABLE Mechanics (
   id LONG GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY,
   first_name VARCHAR(50) NOT NULL,
   second_name VARCHAR(50) NOT NULL,
   last_name VARCHAR(50) NOT NULL,
   payment INTEGER NOT NULL,
   order_statistics INTEGER NOT NULL,
   );
   
CREATE MEMORY TABLE Orders (
   id LONG GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY,
   specification VARCHAR(250) NOT NULL,
   id_customer LONG NOT NULL,
   id_mechanic LONG NOT NULL,
   date_of_creation DATE NOT NULL,
   expiration_date DATE NOT NULL,
   price_of_services INTEGER NOT NULL,
   status VARCHAR(20) NOT NULL,

   CONSTRAINT FK_MechanicOrder FOREIGN KEY (id_mechanic) REFERENCES Mechanics(id),
   CONSTRAINT FK_CustomerOrder FOREIGN KEY (id_customer) REFERENCES Customers(id)
   );